name: CI - DevOps Projects

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: '**/Dockerfile'

      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive || true
